### ISSUE TITLE
Using Testsets with Kotlin in IntelliJ

### ISSUE THREAD

**Issue by mafulafunk** [rishabhdeepsingh/Competitive#5]
Do you have any suggestions on how to set up IntelliJ for Kotlin so that it picks up Testsets in an efficient way?
Maybe I'm just to spoiled by the CHelper Plugin with makes that a 'One-Click' experience for Java in IntelliJ.

**Comment by rishabhdeepsingh** [comment]
I am also looking for the same. BTW **Petr Mitrichev** one of the best coder in the world used CHelper for kotlin I think. Right now we can only use it for Java. 
Will add if I find something.

**Comment by rishabhdeepsingh** [comment]
I have talked to @EgorKulikov what he does is that first writes the code in Java and then convert that code to kotlin. Using intellij Idea convert Java to kotlin. 
Shortcut =  <kbd> Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>Alt</kbd>+<kbd>K</kbd>

**Comment by mafulafunk** [comment]
Doable, but somehow not the most satisfying approach 😂

**Comment by rishabhdeepsingh** [comment]
Most of the people are using simple Kotlin without any templates etc. 
By the way, You can type alias for different structures as I have added to the Kotlin Tab.
